### ISSUE TITLE
Exception when adding a vertical transformation to an image

### ISSUE THREAD

**Issue by bradenrayhorn** [mpdf/mpdf#1079]
### I found this bug / would like to have this new functionality
mPDF throws an exception when a vertical transformation is added to an image.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
`PHP version 7.1.23`
`mPDF version 8.0.1`

Server started using Laravel artisan `serve` command.

### This is a PHP code snippet I use

```php
$mpdf = new Mpdf();

$mpdf->WriteHTML('<html>
<style>
  img {
    max-height: 300px;
    margin-top: 10px;
    transform: translateY(-1px);
  }
</style>
<body>
<img src="https://images.unsplash.com/photo-1567521274654-d463df79f916"/>
</body>
</html>');

$mpdf->Output('invoices.pdf', Destination::FILE);
```

### Trace
```
[2019-09-03 21:16:35] development.INFO: Undefined offset: 1  
[2019-09-03 21:16:35] development.INFO: #0 /Users/name/Documents/project/project-web/vendor/mpdf/mpdf/src/Mpdf.php(7124): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/Users/name/D...', 7124, Array)
#1 /Users/name/Documents/project/project-web/vendor/mpdf/mpdf/src/Mpdf.php(6869): Mpdf\Mpdf->printobjectbuffer(false, 'ltr')
#2 /Users/name/Documents/project/project-web/vendor/mpdf/mpdf/src/Mpdf.php(16284): Mpdf\Mpdf->finishFlowingBlock(true)
#3 /Users/name/Documents/project/project-web/vendor/mpdf/mpdf/src/Mpdf.php(13626): Mpdf\Mpdf->printbuffer(Array)
#4 /Users/name/Documents/project/project-web/app/Models/Invoice.php(116): Mpdf\Mpdf->WriteHTML(' <img src="http...')
#5 /Users/name/Documents/project/project-web/app/Services/EventService.php(171): App\Models\Invoice->createModel(Array)
#6 [internal function]: App\Services\EventService->create(Object(App\Models\Invoice), Array)
#7 /Users/name/Documents/project/project-web/app/Services/EventService.php(137): call_user_func_array(Array, Array)
#8 /Users/name/Documents/project/project-web/app/Http/Controllers/Api/V1/EventsController.php(19): App\Services\EventService->handlePost(Object(Illuminate\Http\Request))
#9 [internal function]: App\Http\Controllers\Api\V1\EventsController->store(Object(Illuminate\Http\Request), Object(App\Services\EventService))
#10 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('store', Array)
#12 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\V1\EventsController), 'store')
#13 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#14 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\Routing\Route->run()
#15 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /Users/name/Documents/project/project-web/app/Http/Middleware/VerifyRoleUuidHeader.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\Http\Middleware\VerifyRoleUuidHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'token')
#21 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/name/Documents/project/project-web/app/Http/Middleware/VerifyAppVersion.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\Http\Middleware\VerifyAppVersion->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#28 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#29 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 /Users/name/Documents/project/project-web/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /Users/name/Documents/project/project-web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 /Users/name/Documents/project/project-web/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 /Users/name/Documents/project/project-web/server.php(21): require_once('/Users/name/D...')
#52 {main}  
```

**Comment by peterdevpl** [comment]
While fixing this issue I also discovered similar notices with `scaleX` and `scaleY`. All fixes are in the same PR.
