### ISSUE TITLE
Exception when using border-color: transparent

### ISSUE THREAD

**Issue by ferow2k** [mpdf/mpdf#1509]
Bug is present using PHP 7.4.23 and Mpdf 8.0.13. 

```php
<?php
$mpdf = new \Mpdf\Mpdf();    
$mpdf->WriteHTML('
  <html>
      <body>
          <div style="border: 1px solid transparent"></div>
      </body>
  </html>
');
```

Stack trace:
```
Exception: Trying to access array offset on value of type bool in /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php:16615
Stack trace:
#1 /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php(16842): Mpdf\Mpdf->_setBorderLine('???', '???')
#2 /var/www/html/vendor/mpdf/mpdf/src/Tag/BlockTag.php(1124): Mpdf\Mpdf->PaintDivBB('???', '???', '???')
#3 /var/www/html/vendor/mpdf/mpdf/src/Tag.php(247): Mpdf\Tag\Div->close('???', '???')
#4 /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php(13718): Mpdf\Tag->CloseTag('???', '???', '???')
#5 Mpdf\Mpdf->WriteHTML('???', '???', '???', '???')
```

Relevant method:
```php
function _setBorderLine($b, $k = 1)
{
    $this->SetLineWidth($b['w'] / $k);
    $this->SetDColor($b['c']);
    if ($b['c'][0] == 5) { // RGBa <== Error thrown because $b['c'] === false
        $this->SetAlpha(ord($b['c'][4]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
    } elseif ($b['c'][0] == 6) { // CMYKa
        $this->SetAlpha(ord($b['c'][5]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
    }
}
```
Possible fix:
```php
function _setBorderLine($b, $k = 1)
{
    $this->SetLineWidth($b['w'] / $k);
    $this->SetDColor($b['c']);
    if ($b['c']===false)
        return;
    if ($b['c'][0] == 5) { // RGBa
        $this->SetAlpha(ord($b['c'][4]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
    } elseif ($b['c'][0] == 6) { // CMYKa
        $this->SetAlpha(ord($b['c'][5]) / 100, 'Normal', false, 'S'); // mPDF 5.7.2
    }
}
```

**Comment by taist24** [comment]
Any updates on this?
