### ISSUE TITLE
When setting in the CSS the font-family to Serif or Sans-Serif Mpdf throws an Error 

### ISSUE THREAD

**Issue by tkfv** [mpdf/mpdf#1563]
### I found this bug

I rely on core fonts and `fontDir` is set to `[]`. If in the CSS I set a random font like `font-family: foo`, the pdf is generated without a problem with the default font (ctimes). If instead I set `font-family: Serif` or `font-family: Sans-Serif` the following error is thrown:

```
PHP Warning:  Undefined array key 0 in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1695
PHP Warning:  Undefined array key 0 in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1695
PHP Warning:  Trying to access array offset on value of type null in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3544
PHP Warning:  Undefined array key "type" in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 3544
PHP Warning:  Undefined array key "desc" in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 10995
PHP Warning:  Undefined array key "desc" in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 11139
PHP Warning:  Undefined array key 0 in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1695
PHP Warning:  Undefined array key 0 in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1695
PHP Warning:  Undefined array key 0 in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1695
PHP Warning:  Undefined array key "type" in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Writer/FontWriter.php on line 113
PHP Warning:  Undefined array key "name" in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Writer/FontWriter.php on line 114
PHP Fatal error:  Uncaught Mpdf\MpdfException: Unsupported font type:  () in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Writer/FontWriter.php:438
Stack trace:
#0 /home/dn/testmpdf/vendor/mpdf/mpdf/src/Writer/ResourceWriter.php(113): Mpdf\Writer\FontWriter->writeFonts()
#1 /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php(10001): Mpdf\Writer\ResourceWriter->writeResources()
#2 /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php(2048): Mpdf\Mpdf->_enddoc()
#3 /home/dn/testmpdf/vendor/mpdf/mpdf/src/Mpdf.php(9484): Mpdf\Mpdf->Close()
#4 /home/dn/testmpdf/test.php(10): Mpdf\Mpdf->Output()
#5 {main}
  thrown in /home/dn/testmpdf/vendor/mpdf/mpdf/src/Writer/FontWriter.php on line 438

```

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using

mPDF 8.0.15
PHP 8.0.12 cli

### This is the PHP code snippet I use

```
<?php
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new \Mpdf\Mpdf([
'tempDir' => sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'mpdf',
'fontDir' => [],
'fontdata' => [],
'default_font' => 'ctimes',
]);
$mpdf->WriteHTML( '<style>p {font-family: Serif; }</style><p>hello</p>' );
$mpdf->Output( '/tmp/out.pdf' );
```

### This is the HTML/CSS code snippet I use

The following doesn't work:

```
'<style>p {font-family: Serif; }</style><p>hello</p>'
```

Nor this:

```
'<style>p {font-family: San-Serif; }</style><p>hello</p>'
```

This one does

```
'<style>p {font-family: foo; }</style><p>hello</p>'
```

**Comment by finwe** [comment]
As noted in the original issue, use correct `mode` of `c` to use only core fonts. Removing information about font paths will inevitably break the program flow.

https://mpdf.github.io/fonts-languages/choosing-a-configuration-v7-x.html#1-core-non-embedded-fonts
