### ISSUE TITLE
Notice: Undefined offset: -1 in Mpdf\Tag\BlockTag->open()

### ISSUE THREAD

**Issue by Phyzyx** [mpdf/mpdf#1655]
When calling `Mpdf->WriteHTML()`, we get the following notice:

`Notice: Undefined offset: -1 in Mpdf\Tag\BlockTag->open()`

Here's the full stack trace:

`
#0 /var/www/ezcompany/rocmn/htdocs/core/includes/bootstrap.inc(312): _drupal_error_handler_real(8, 'Undefined offse...', '/var/www/ezcomp...', 118)
#1 /var/www/ezcompany/rocmn/vendor/mpdf/mpdf/src/Tag/BlockTag.php(118): _drupal_error_handler(8, 'Undefined offse...', '/var/www/ezcomp...', 118, Array)
#2 /var/www/ezcompany/rocmn/vendor/mpdf/mpdf/src/Tag.php(243): Mpdf\Tag\BlockTag->open(Array, Array, 503)
#3 /var/www/ezcompany/rocmn/vendor/mpdf/mpdf/src/Mpdf.php(13634): Mpdf\Tag->OpenTag('H3', Array, Array, 503)
#4 /var/www/ezcompany/rocmn/htdocs/modules/custom/rocmnmod/src/Controller/RocmnmodNodePdf.php(118): Mpdf\Mpdf->WriteHTML(' <div class="co...')
#5 [internal function]: Drupal\rocmnmod\Controller\RocmnmodNodePdf->generatePdf(Object(Drupal\node\Entity\Node))
#6 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#7 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/Render/Renderer.php(578): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#8 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#9 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#10 /var/www/ezcompany/rocmn/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#11 /var/www/ezcompany/rocmn/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#12 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/ezcompany/rocmn/htdocs/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/ezcompany/rocmn/htdocs/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/ezcompany/rocmn/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/www/ezcompany/rocmn/htdocs/core/lib/Drupal/Core/DrupalKernel.php(717): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/www/ezcompany/rocmn/htdocs/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#21 {main}
`

We're using mPDF at 7.1.9, PHP 7.3.19-1+0~20200612.60+debian10~1.gbp6c8fe1 and Nginx 1.14.2

Here's the function calling `WriteHTML()`:

```
<?php
  /**
   * Generates a pdf for a given node.
   *
   * @param \Drupal\Node\NodeInterface $node
   *   The node entity to generate the pdf for.
   *
   * @return \Drupal\Core\Cache\CacheableResponse|\Drupal\Core\Routing\TrustedRedirectResponse
   *   The response object.
   */
  public function generatePdf(NodeInterface $node) {
    $domain_id = _rocmnmod_get_domain_for_current_node($node);
    if ($domain_id != _rocmnmod_get_active_domain_id()) {
      // Mark this redirect as being uncacheable.
      \Drupal::service('page_cache_kill_switch')->trigger();

      /** @var \Drupal\domain\DomainInterface $domain */
      $domain = $this->entityTypeManager()->getStorage('domain')->load($domain_id);
      return new TrustedRedirectResponse($domain->getUrl(), 301);
    }

    $view_builder = $this->entityTypeManager()->getViewBuilder($node->getEntityTypeId());
    $render = $view_builder->view($node, 'pdf');
    $html = $this->renderer->renderRoot($render);

    $mpdf = $this->getMpdf($node->label());
    $mpdf->SetImportUse();
    $mpdf->SetDocTemplate($this->getTemplatePdf($node), TRUE);
    $mpdf->WriteHTML($html);
    ...
```

And the `getTemplatePdf()` function:

```
<?php
  /**
   * Generate a pdf for a given node and return its filename.
   *
   * @param \Drupal\Node\NodeInterface $node
   *   The node entity to get the pdf template for.
   *
   * @return string
   *   An absolute url string to the pdf file.
   */
  protected function getTemplatePdf(NodeInterface $node) {
    $domain_id = _rocmnmod_get_active_domain_id();
    $cid = 'rocmnmod-template-pdf-' . $domain_id . '-' . $node->id();
    $filename = DRUPAL_ROOT . '/../mpdf/template-pdfs/' . $cid . '.pdf';

    if (\Drupal::cache()->get($cid) && file_exists($filename)) {
      return $filename;
    }

    $title = $node->getTitle();
    $header_image_entity = NULL;
    $header_image_url = '';

    if (!$node->get('field_header_image')->isEmpty()) {
      $header_image_entity = $node->get('field_header_image')->entity;
    }
    else {
      $landing_page = _rocmnmod_get_domain_landing_page_node();
      if ($landing_page && !$landing_page->field_header_image->isEmpty()) {
        $header_image_entity = $landing_page->field_header_image->entity;
      }
    }

    if ($header_image_entity instanceof FileInterface) {
      $header_image_style = 'header_pdf';

      $file_uri = $header_image_entity->getFileUri();
      $header_image_url = ImageStyle::load($header_image_style)->buildUrl($file_uri);

      if (_rocmnmod_get_default_domain_id() !== _rocmnmod_get_active_domain_id()) {
        /** @var \Drupal\domain\Entity\Domain $default_domain */
        $default_domain = _rocmnmod_get_default_domain();

        $image_url = file_url_transform_relative(file_create_url($header_image_url));
        $header_image_url = $default_domain->buildUrl($image_url);
      }
    }

    $communication_uri = $this->getCommunicationUri($domain_id);
    $communication_url = Url::fromUri('http://' . $communication_uri, ['attributes' => ['class' => ['url']]]);
    $communication_link = Link::fromTextAndUrl($communication_uri, $communication_url);

    $render = [
      '#theme' => 'rocmnmod__node_template_pdf',
      '#pdf_domain_id' => $domain_id,
      '#header_image' => $header_image_url,
      '#communication_link' => $communication_link->toRenderable(),
      '#title' => $title,
    ];

    // For simplicity, this bo-specific #theme is set here instead of
    // duplicating a lot of code.
    if (_rocmnbo_is_bo_domain()) {
      $render['#theme'] = 'rocmnbo__node_template_pdf';
    }

    $html = $this->renderer->renderRoot($render);

    $mpdf = $this->getMpdf($title);

    $mpdf->img_dpi = 300;
    $mpdf->WriteHTML($html);

    $mpdf->Output($filename, Destination::FILE);
    \Drupal::service('file_system')->chmod($filename, 0664);

    $cache_tags = Cache::mergeTags($node->getCacheTags(), [
      'state:domain_settings',
      'config:domain.record.' . $domain_id,
    ]);

    \Drupal::cache()->set($cid, 1, Cache::PERMANENT, $cache_tags);

    return $filename;
  }
```

As you can tell by the stack trace and code snippets, we're using Drupal at 9.2.13. My suspicion is that this happens when trying to render a table from a WYSIWYG editor. Drupal uses CKEditor for that. I've tried including a table in the editor, but wasn't able to reproduce the notice this way. Any idea what might be causing this? Thanks in advance.

**Comment by finwe** [comment]
Share a reproducible piece of code, a HTML snippet causing this.

**Comment by JPurinsh** [comment]
@finwe Here you go:

This HTML to PDF conversion fails:

```
<img src="https://qckinetix-munbs.formstack.com/forms/images/3/formstack_icon.png" style="width: 24px !important; height: 22px !important; vertical-align: middle !important;" />
```

But this one works:

```
<img src="https://qckinetix-munbs.formstack.com/forms/images/3/formstack_icon.png" style="width: 24px; height: 22px; vertical-align: middle;" />
```

So the issue seems to be with the "!important" tags in inline CSS.

Can this be fixed, please? Thank you!


FYI @webmasterMeyers
