### ISSUE TITLE
mPDF crashes on mkdir for its cache directory

### ISSUE THREAD

**Issue by adlcadn** [mpdf/mpdf#1775]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

I use Mpdf via composer ("mpdf/mpdf": "~8.1") and I regularly have an error related to the creation (sometimes the deletion) of a Cache directory because having many PDF files to create, the processor launches several concurrent processes. 
It seems that the Cache directory being unique for all processes, it regularly happens that the directory has just been created by a process A and that another process also tries to create it. 
What solution can we find to avoid this problem? 
Shouldn't the cache directory be private to each process, for example by giving a name based on a random string?

Here is the stack of the error received:

> ERROR:  ErrorException: mkdir(): File exists in /var/app/current/vendor/mpdf/mpdf/src/Cache.php:49 Stack trace:
> #0 [internal function]: log_error(2, 'mkdir(): File e...', '/var/app/curren...', 49)
> #1 /var/app/current/vendor/mpdf/mpdf/src/Cache.php(49): mkdir('/var/app/curren...')
> #2 /var/app/current/vendor/mpdf/mpdf/src/Cache.php(35): Mpdf\Cache->createDirectory('/var/app/curren...')
> #3 /var/app/current/vendor/mpdf/mpdf/src/Cache.php(20): Mpdf\Cache->createBasePath('/var/app/curren...')
> #4 /var/app/current/vendor/mpdf/mpdf/src/ServiceFactory.php(67): Mpdf\Cache->__construct('/var/app/curren...', 3600)
> #5 /var/app/current/vendor/mpdf/mpdf/src/Mpdf.php(1083): Mpdf\ServiceFactory->getServices(Object(Mpdf\Mpdf), Object(Psr\Log\NullLogger), Array, Object(Mpdf\Language\LanguageToFont), Object(Mpdf\Language\ScriptToLanguage), NULL, NULL, NULL, NULL)
> #6 /var/app/current/src/docs/pdfRelevePP.php(109): Mpdf\Mpdf->__construct(Array)
> #7 /var/app/current/src/index.php(361): makePdfRelevePP(Array) #8 {main}  

### mPDF version

8.1

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

PHP 8.0 running on 64bit Amazon Linux 2/3.5.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
$mpdf = new \Mpdf\Mpdf( [ 
        'debug' => true,
        'allow_output_buffering' => true ] );  // <-- ERROR
$mpdf->allow_charset_conversion = true;
$mpdf->charset_in = 'utf-8';
$mpdf->setFooter( '{PAGENO} de {nbpg}' );
$mpdf->WriteHTML( $html );
$pdf_gen = $mpdf->Output( '', \Mpdf\Output\Destination::STRING_RETURN );
```

**Comment by brainfoolong** [comment]
The directory is only been created if it not exist. The cache directory itself is shared by default and should always be present and never be deleted (It wouldn't be deleted by mpdf itself). So it should never need to create it in the first place, unless you specific custom directories that are not yet exist.

All files in the cache directory itself are prefixed and generated with a unique random name for each file in it, so file collisions are almost impossible even if you run 10.000 processes at the same time.

As far as i can see how MPDF uses cache directories. Hope this helps. We never have this issues, and we also do create a lot pdfs with this library.

**Comment by thorewi** [comment]
Hi,

this happens to me after deploy... I can create cache directory after deploy manually, but there are also other files, which are not unique:

<img width="733" alt="Screenshot 2024-07-23 at 10 54 24" src="https://github.com/user-attachments/assets/ab27775f-4e9e-459e-9338-594a0d95edfc">
