### ISSUE TITLE
Error: Undefined array key

### ISSUE THREAD

**Issue by banine** [mpdf/mpdf#1822]
### Guidelines

- [X] I understand that [if I fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

<html>
<body>

```
{
  "name": "PHP Warning",
  "message": "Undefined array key 0",
  "code": 2,
  "type": "yii\\base\\ErrorException",
  "file": "/home/api2cicsb/public_html/rest/vendor/mpdf/mpdf/src/Tag/BlockTag.php",
  "line": 117,
  "stack-trace": [
    "#0 /home/api2cicsb/public_html/rest/vendor/mpdf/mpdf/src/Tag/BlockTag.php(117): yii\\base\\ErrorHandler->handleError(2, 'Undefined array...', '/home/api2cicsb...', 117)",
    "#1 /home/api2cicsb/public_html/rest/vendor/mpdf/mpdf/src/Tag.php(240): Mpdf\\Tag\\BlockTag->open(Array, Array, 299)",
    "#2 /home/api2cicsb/public_html/rest/vendor/mpdf/mpdf/src/Mpdf.php(13892): Mpdf\\Tag->OpenTag('DIV', Array, Array, 299)",
    "#3 /home/api2cicsb/public_html/rest/controllers/PdfController.php(60): Mpdf\\Mpdf->WriteHTML(' <div id=\"water...')",
    "#4 [internal function]: rest\\controllers\\PdfController->actionGenerate()",
    "#5 /home/api2cicsb/public_html/rest/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
    "#6 /home/api2cicsb/public_html/rest/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)",
    "#7 /home/api2cicsb/public_html/rest/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('generate', Array)",
    "#8 /home/api2cicsb/public_html/rest/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('pdf/generate', Array)",
    "#9 /home/api2cicsb/public_html/rest/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
    "#10 /home/api2cicsb/public_html/rest/web/index.php(10): yii\\base\\Application->run()",
    "#11 {main}"
  ]
}
```
</body>
</html>

### mPDF version

8.1.4

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

cpanel apache php8.1

### Reproducible PHP+CSS+HTML snippet suffering by the error

```<style> td{padding-right: 10px; padding-left: 10px; padding-bottom: 5px;} #watermark { position: fixed; top: 30px; right: -125px; width: 900px; height: 900px; } img { opacity: 0.2; filter: alpha(opacity=50); /* For IE8 and earlier */ } </style> <div id="watermark"><img src="/cic/www/admin/img/juwara.png" width="100%" alt="watermark logo"></div> <table border="0" style="width:100%; border-collapse: collapse;"> <tr> <td> <!--<img width="170" height="50" src="/cic/www/admin/img/juwara.png">--> </td> <td align="right"><font size="5"><b>Payslip For</b><font></td> </tr> <tr> <td><b><font size="5">Juwara xxxxxxxxxxx Sdn Bhd</font></b></td> <td align="right"><font size="5"><b> Dec-2022 </b><font></td> </tr> <tr><td></td></tr> </table> <div class="form"> <table class="table"> <tr> <td>NAME :</td> <td width="250"> Mxxxxx </td> <td>NEW IC NO :</td> <td>Cxxxxx</td> </tr> <tr> <td>DESIGNATION :</td> <td>ENV-TECH - G01</td> <td>DATE JOINED :</td> <td></td> </tr> <tr> <td>DEPARTMENT :</td> <td>BADAN PENGURUSAN BERSAMA PARAGON SOLSTICE </td><!--aini edit 13/9/2016--> <td>BANK A/C :</td> <td>7xxxxxxxxxx6</td> </tr> </table> <br/> <table border="1" style="width:100%; border-collapse: collapse;"> <tr> <td style="width:35%;">GROSS EARNING</td> <td>Amount (RM)</td> <td style="width:35%;">DEDUCTIONS</td> <td>Amount (RM)</td> </tr> <tr> <td style="height:25%;vertical-align: text-top;"> BASIC SALARY<br>OVERTIME NORMAL<br>PROJECT ALLOWANCE<br> </td> <td align="right" valign="top">x,xxx.xx<br>xxx.xx<br>xxx.xx<br></td> <td valign="top">ADVANCE PERMIT<br>KELAB KRKJ<br></td> <td align="right" valign="top">xxx.xx<br>x.xx<br></td> </tr> <tr> <td>TOTAL EARNING / INCOME</td> <td align="right">x,xxx.xx</td> <td>TOTAL DEDUCTIONS</td> <td align="right">xxx.xx</td> </tr> <tr> <td></td> <td></td> <td>EMPLOYER CONTRIBUTIONS</td> <td></td> </tr> <tr> <td style="height:10%;">NETT PAY</td> <td align="right">x,xxx.xx</td> <td>SOCSO EMPLOYER<br></td> <td align="right">xx.xx<br></td> </tr> </table> <br/><br/> <!-- <table style="width:100%"> <tr align="right"> <td>............................................................................</td> </tr> <tr align="right"> <td>Employee Signature</td> </tr> </table>--> <!-- <table style="width:100%"> <tr align="centre"> <td><b></b></td> </tr> </table>--> </div><!-- form --> <div class="col col-12"> <div class = "row"> <div class = "col-5"> <div class="col-5"> <!-- Default panel contents --> <h2>Monthly Performance Review</h2><br /> <table border="1" class="table table-bordered"> <thead> <tr> <div id="w0" class="list-view"> <div data-key="52745"><td> DISIPLIN</td> </div> <div data-key="52746"><td> KEMASAN DIRI</td> </div> <div data-key="52747"><td> PATUH ARAHAN</td> </div> <div data-key="52748"><td> CEKAP DAN MAHIR</td> </div> </div> </tr> </thead> <tr> <div id="w1" class="list-view"> <div data-key="52745"><td>4</td> </div> <div data-key="52746"><td>4</td> </div> <div data-key="52747"><td>4</td> </div> <div data-key="52748"><td>4</td> </div> </div> </tr> </table> </div> </div> <div class = "col-1"></div> <div class = "col-5"> <div class="table-responsive col-md-6"> <!-- Default panel contents --> <h2>Advance Permit</h2>31-01-2022 - 30-04-2023 <table border="1" class="table table-bordered col-md-6"> <thead> <tr> <td>ADVANCE PERMIT</td> <td>DEDUCTED</td> <td>BALANCE</td> </tr> </thead> <tr> <td>xxxx.xx</td> <td>xxx.xx</td> <td>xxx.xx</td> </tr> </table> </div> </div> </div> </div> </div>```

this is the $html content send to $mpdf->WriteHTML($html);

**Comment by finwe** [comment]
You have invalid HTML in your markup, opened and unclosed <font> tags. Not that mPDF should crash on this, but that is probably the reason for the notice.

**Comment by banine** [comment]
Thanks, warning gone when the tag font closed properly.

**Comment by finwe** [comment]
I'll leave open for potential fix.
