### ISSUE TITLE
Getting Fatal error sometimes with the ColorConverter

### ISSUE THREAD

**Issue by Ibrahim-Aboubacar** [mpdf/mpdf#2006]
### Guidelines

- [X] I understand that [if I fail to adhere to contribution guidelines and/or fail to provide all required details, this issue may be closed without review](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md).

### Description of the bug

Warning: Undefined array key 1 in ...\vendor\mpdf\mpdf\src\Color\ColorConverter.php on line 245
Warning: Undefined array key 2 in ...\vendor\mpdf\mpdf\src\Color\ColorConverter.php on line 245

Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in ...\vendor\mpdf\mpdf\src\Color\ColorConverter.php:60 Stack trace: 0 ...\vendor\mpdf\mpdf\src\Color\ColorConverter.php(60): round('') #1 ...\vendor\mpdf\mpdf\src\Mpdf.php(19001): Mpdf\Color\ColorConverter->convert('rgb(59 130 246 ...', Array) #2 ...\vendor\mpdf\mpdf\src\Tag\A.php(38): Mpdf\Mpdf->setCSS(Array, 'INLINE') #3 ...\vendor\mpdf\mpdf\src\Tag.php(240): Mpdf\Tag\A->open(Array, Array, 19) #4 ...\vendor\mpdf\mpdf\src\Mpdf.php(13921): Mpdf\Tag->OpenTag('A', Array, Array, 19) #5 ...\admin\makepdf.php(213): Mpdf\Mpdf->WriteHTML(' <header class=...') #6 {main} thrown in ...\vendor\mpdf\mpdf\src\Color\ColorConverter.php on line 60

### mPDF version

8.2.3

### PHP Version and environment (server type, cli provider etc., enclosing libraries and their respective versions)

8.2

### Reproducible PHP+CSS+HTML snippet suffering by the error

```
<?php

use Mpdf\Mpdf;

require_once dirname(__DIR__) . "/vendor/autoload.php";
if (isset($_POST) && isset($_POST['survey'])) :
    $id = (int)$_POST['survey'];
    $survey = getSurveyByid($id);
    if (!$survey) {
    }
    // dd($survey);
    ob_start();
?>
    <!DOCTYPE html>
    <html lang="fr">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $survey["compagny_name"] ?> - Inscription mon entreprise en .NE</title>
        <link rel="icon" type="image/x-icon" href="../img/logo.png">
        <link rel="stylesheet" href="../css/style.css">
    </head>

    <body>
        <header class="max-w-screen-xl mx-auto pt-4 text-lg">
            <nav>
                <ul class="flex flex-col px-5 items-start gap-0 justify-center">
                    <li><img class="w-20" src="../img/logo.png" alt=""></li>
                    <li class="font-bold">SOLUNIX GROUPS</li>
                    <li class="font-medium">Tél: <a class="underline text-blue-500" href="tel:+22783408696">+227 83 40 86 96</a></li>
                    <li class="font-medium">Hotline: <a class="underline text-blue-500" href="tel:+22797573907">+227 97 57 39 07</a></li>
                    <li class="font-medium">Site Web: <a class="underline text-blue-500" href="https://www.solunixgroups.africa">www.solunixgroups.africa</a></li>
                    <li class="font-medium">contact: <a class="underline text-blue-500" href="mailto:kaze@solunixgroups.africa">kaze@solunixgroups.africa</a></li>
                </ul>
            </nav>
        </header>
        <h1 class="max-w-screen-xl mx-auto text-center underline text-2xl font-semibold uppercase mt-10">
            <?= $survey["compagny_name"] ?> - Inscription mon entreprise en .NE
        </h1>
        <section class="max-w-screen-xl mx-auto grid grid-cols-2 gap-5 mt-10">
            <div class="col-span-2 px-3">
                <h2 class="py-3 font-semibold text-xl">Données Formulaire</h2>
                <table class="table-auto_ w-full text-lg">
                    <thead>
                        <tr class="bg-gray-600 text-gray-100">
                            <th scope="col" class="border-r border-gray-700 w-1/2">Champs</th>
                            <th scope="col" class=" w-1/2">Valeur</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Nom de l'entreprise -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Nom de l'entreprise</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["compagny_name"] ?></span></td>
                        </tr>
                        <!-- Numéro IFU (NIF) -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Numéro IFU (NIF)</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["ifu_number"] ?></span></td>
                        </tr>
                        <!-- Date de création -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Date de création</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= date('D d M Y à H:i:s', strtotime($survey["created_date"])) ?></span></td>
                        </tr>
                        <!-- Date de debut d'activité -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Date de debut d'activité</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= date('D d M Y à H:i:s', strtotime($survey["activity_start_date"])) ?></span></td>
                        </tr>
                        <!-- Numéro IFU (NIF) -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Numéro IFU (NIF)</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["ifu_number"] ?></span></td>
                        </tr>
                        <!-- Statu l'égal -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Statu l'égal</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["legal_status"] ?></span></td>
                        </tr>
                        <!-- Secteur d'activité -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Secteur d'activité</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["activity_sector"] ?></span></td>
                        </tr>
                        <!-- Activité principal -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Activité principal</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["main_activity"] ?></span></td>
                        </tr>
                        <!-- Nom et prénoms du Dirigeant -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Nom et prénoms du Dirigeant</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["director_fullname"] ?></span></td>
                        </tr>
                        <!-- Département (siège) -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Département (siège)</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["city"] ?></span></td>
                        </tr>
                        <!-- Numéro de téléphone -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Numéro de téléphone</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["phone_number"] ?></span></td>
                        </tr>
                        <!-- Addresse -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Addresse</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["address"] ?></span></td>
                        </tr>
                        <!-- Email -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Email</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["email_address"] ?></span></td>
                        </tr>
                        <!-- Email -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Email</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["email_address"] ?></span></td>
                        </tr>
                        <!-- Site internet -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Site internet</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["web_site"] ?></span></td>
                        </tr>
                        <!-- Nom et Prénom du demandeur -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Nom et Prénom du demandeur</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["contact_fullname"] ?></span></td>
                        </tr>
                        <!-- Numéro de téléphone du demandeur -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Numéro de téléphone du demandeur</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["contact_number"] ?></span></td>
                        </tr>
                        <!-- Email du demandeur -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Email du demandeur</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["contact_email_address"] ?></span></td>
                        </tr>
                        <!-- Comment avez-vous entendu parler de cette initiative -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Comment avez-vous entendu parler de cette initiative</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["how_head_us"] ?></span></td>
                        </tr>
                        <!-- Que dites-vous de Solunix Niger? -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Que dites-vous de Solunix Niger?</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["what_u_think"] ?></span></td>
                        </tr>
                        <!-- Autorisation de collecte de données -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Autorisation de collecte de données</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["collect_data"] == 1 ? 'OUI' : 'NON' ?></span></td>
                        </tr>
                        <!-- Email -->
                        <!-- <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Email</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["email_address"] ?></span></td>
                        </tr> -->

                    </tbody>
                </table>
            </div>
            <div class="col-span-2 px-3">
                <h2 class="py-3 font-semibold text-xl">Données appareil utilisateur</h2>
                <table class="table-auto_ w-full text-lg">
                    <thead>
                        <tr class="bg-gray-600 text-gray-100">
                            <th scope="col" class="border-r border-gray-700 w-1/2">Champs</th>
                            <th scope="col" class=" w-1/2">Valeur</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Pays d'inscription -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Pays d'inscription</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["ip_country_name"] ?></span></td>
                        </tr>
                        <!-- Region d'inscription -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Region d'inscription</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["ip_region_name"] ?></span></td>
                        </tr>
                        <!-- Region -->
                        <tr class="odd:bg-gray-300 odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Region</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= $survey["ip_city"] ?></span></td>
                        </tr>
                        <!-- Date d'inscription -->
                        <tr class="odd:bg-gray-300 border-b odd:border-gray-200">
                            <td class="border-r border-gray-700"><span class="block px-4 py-2 w-full min-w-max font-semibold">Date d'inscription</span></td>
                            <td><span class="block px-4 py-2 w-max max-w-48"><?= date('D d M Y à H:i:s', strtotime($survey["created_at"])) ?></span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </section>
        <p class="py-28 text-center">SOLUNIX GROUPS</p>
    </body>

    </html>
<?php
    $html = ob_get_clean();

    // echo "hi";
    $pdf = new Mpdf();
    $pdf->SetTitle($survey["id"] . " - " . $survey["compagny_name"] . " - Inscription mon entreprise en .NE");
    $pdf->SetAuthor("SolunixGroups");
    $pdf->writeHTML($html);
    $pdf->Output();
endif;

```

**Comment by Ibrahim-Aboubacar** [comment]
In the file ColorConverter, by casting the $c[INDEX] variable to int, the problem is fixed

```
$cstr = pack(
	'a1ccccc',
	$c[0],
	round((int)$c[1]) & 0xFF,
	round((int)$c[2]) & 0xFF,
	round((int)$c[3]) & 0xFF,
	round((int)$c[4]) & 0xFF,
	round((int)$c[5]) & 0xFF
);
```

**Comment by ssieb** [comment]
Create a **minimal** example.
