### ISSUE TITLE
`!important` breaks SizeConverter.php on line 35

### ISSUE THREAD

**Issue by cliffordp** [mpdf/mpdf#524]
### I found this bug

HTML with `!important` in it causes this PHP Fatal Error:
> Fatal error: Uncaught exception 'Mpdf\MpdfException' with message 'Invalid size representation' in .../vendor/mpdf/mpdf/src/SizeConverter.php on line 35

I did a `str_ireplace()` to remove all `100% !important` but then the error message just said `!important` (no unit before it) so instead I just removed all `!important` (so `width: 100% !important` would become `width: 100%`) and that solved it and the PDF's layout was still fine.

### This is mPDF and PHP version and environment (fpm/cli etc) I am using
mPDF version 7.0.1
PHP version 5.6.20

ran mPDF simply as `new \Mpdf\Mpdf( array( 'c' ) );`

Here is the stack trace:
```
[28-Oct-2017 01:36:13 UTC] PHP Fatal error:  Uncaught exception 'Mpdf\MpdfException' with message 'Invalid size representation "100% !important"' in .../vendor/mpdf/mpdf/src/SizeConverter.php:35
Stack trace:
#0 .../vendor/mpdf/mpdf/src/Mpdf.php(19755): Mpdf\SizeConverter->convert('100% !important', 180.00155555556, 3.7041666666667, false)
#1 .../vendor/mpdf/mpdf/src/Tag.php(2091): Mpdf\Mpdf->setCSS(Array, 'BLOCK', 'DIV')
#2 .../vendor/mpdf/mpdf/src/Mpdf.php(15282): Mpdf\Tag->OpenTag('DIV', Array, Array, 1)
#3 .../index.php(770): Mpdf\Mpdf->WriteHTML('<!DOCTYPE html ...')
#4 .../index.php(735): Tribe__Extension__PDF_Tickets->get_mpdf('<!DOCTYPE html ...')
#5 .../index.php(566): Tribe__Extension__PDF_Tickets->output_pd in .../vendor/mpdf/mpdf/src/SizeConverter.php on line 35
```

**Comment by finwe** [comment]
Please, provide an example of HTML/CSS code that causes this.

    new \Mpdf\Mpdf( array( 'c' ) );

Does not make sense, it should be at least

    new \Mpdf\Mpdf( array( 'mode' => 'c' ) );

or the 'c' is ignored as number-indexed parameter.

**Comment by cliffordp** [comment]
Thanks for correcting my `mode` code. Sorry about that.

The exact same debug message still happens with `new \Mpdf\Mpdf( array( 'mode' => 'c' ) );`

Here's a copy of one of the HTML documents that is causing this: https://cl.ly/452R3x0M2L19
It validates except for 4 `there is no attribute ___` errors because this same HTML gets sent as an HTML email and I'm just trying to replicate it in the form of a PDF.

**Comment by aluferraz** [comment]
+1 

Same issue here.

**Comment by webbed88** [comment]
+1

**mPDF Version:** 7.0.1
**PHP Version:** 7.1.10
**HTML:** `<a href="#" style="text-shadow: none !important;}">Test Link</a>`
**Error Message:** `Fatal error: Uncaught Mpdf\MpdfException: Invalid size representation "!important" in ../vendor/mpdf/mpdf/src/SizeConverter.php on line 35`

**Comment by kspal** [comment]
+1 ;
i use this patch : 
`$size=str_replace('!important','',$size); `
before line 33 : 
`$size = trim(strtolower($size));`

**Comment by radius314** [comment]
When will you be cutting a new release?

**Comment by finwe** [comment]
Soon, during the following week, I guess. If it is not out on thursday, feel free to remind me.

**Comment by radius314** [comment]
Awesome thanks!  Looking forward to it.

**Comment by radius314** [comment]
Btw, this patch works great.

**Comment by radius314** [comment]
Will you be cutting a version tonight?

**Comment by finwe** [comment]
7.1.0 is out https://github.com/mpdf/mpdf/releases/tag/v7.1.0 @radius314

**Comment by radius314** [comment]
👍
