### ISSUE TITLE
Undefined index y0 and x0 in Mpdf.php

### ISSUE THREAD

**Issue by stupidusername** [mpdf/mpdf#584]
I've found these errors on version 7.0.2 on lines 2849 and 2920. What do you need to reproduce the errors? The stack trace for both errors is the same. I'll leave it down below.

`#0 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(2849): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/bukmar...', 2849, Array)
#1 /var/www/bukmark/vendor/mpdf/mpdf/src/Tag.php(2118): Mpdf\Mpdf->AddPage('P')
#2 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(15298): Mpdf\Tag->OpenTag('DIV', Array, Array, 1)
#3 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(9528): Mpdf\Mpdf->WriteHTML(' <div style="ba...', 4)
#4 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(11311): Mpdf\Mpdf->_puthtmlheaders()
#5 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(1994): Mpdf\Mpdf->_enddoc()
#6 /var/www/bukmark/vendor/mpdf/mpdf/src/Mpdf.php(9224): Mpdf\Mpdf->Close()
#7 /var/www/bukmark/vendor/kartik-v/yii2-mpdf/Pdf.php(394): Mpdf\Mpdf->Output('', 'D')
#8 /var/www/bukmark/vendor/kartik-v/yii2-mpdf/Pdf.php(265): kartik\mpdf\Pdf->output('\n<br>\n\n\n\t\n\t\n\t<d...', '', 'D')
#9 /var/www/bukmark/controllers/EstimateController.php(453): kartik\mpdf\Pdf->render()
#10 [internal function]: app\controllers\EstimateController->actionGetPdf('10593')
#11 /var/www/bukmark/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/bukmark/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/bukmark/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('get-pdf', Array)
#14 /var/www/bukmark/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('estimate/get-pd...', Array)
#15 /var/www/bukmark/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 /var/www/bukmark/web/index.php(16): yii\base\Application->run()`

**Comment by Klap-in** [comment]
How is Mpdf instantiated in your setup?
Which html is feeded into mPDF, such that it triggers these errors?

That helps to reproduce it, and allows to write unit tests. Thanks!

**Comment by stupidusername** [comment]
This are the options used to instantiate Mpdf:

`Array
(
    [autoPageBreak] => 
    [setAutoTopMargin] => pad
    [setAutoBottomMargin] => pad
    [mode] => UTF-8
    [format] => A4
    [default_font_size] => 0
    [default_font] => 
    [margin_left] => 0
    [margin_right] => 0
    [margin_top] => 0
    [margin_bottom] => 0
    [margin_header] => 0
    [margin_footer] => 0
    [orientation] => P
    [tempDir] => /var/www/bukmark/runtime/mpdf
)`

This is the HTML code:

`<html><head><style></style></head><body><br>


	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>E817</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Set Ideal para Notebook/Netbook/PC. Incluye un mouse inalámbrico de excelente diseño, una luz portátil conexión usb con Led de alta luminosidad y un par de auriculares supraaurales de alta fidelidad. Todo en un necessaire semirigido negro. Medidas Set cerrado 17cm x 14cm x 6cm									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 532,27				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>E449</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Auriculares Bluetooth plegables, cuentan con microfono incorporado para función manos libres, soporte para entrada auxiliar (miniplug 3.5mm) y batería de litio. Colores disponibles: azul, verde y gris.									<br>
					Incluye logo full color en ambos lados.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 798,20				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>H457</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Set de herramienta orange en estuche de cuero ecológico									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 287,05				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M676</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila portanotebook wagner stadt confeccionada en 1680D poliéster. Capacidad: 18 litros. Posee un compartimento principal integrado para notebook debidamente acolchado para mayor seguridad. Correas para hombros acolchadas.									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 887,38				</div>
								</div>
	</div>

			<hr>
	
	
			<pagebreak>
			
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M696</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila wagner arth. Varios compartimientos y bolsillos. Correas ajustables. Zippers metálicos. Espaldar anatómico y acolchado. Capacidad: 40 litros									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 919,17				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M662</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila portanotebook wagner moon confeccionada en 1680D poliéster. Varios compartimientos. Correas para hombros ajustables y acolchadas. Capacidad: 18 litros									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 1189,38				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M697</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila wagner bruck. Varios compartimientos y bolsillos. Integramente forrada. Espaldar anatómico y acolchado. Capacidad: 40 litros									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 1205,27				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M900</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila portanotebook wagner leck luxus, confeccionada en waterpoof taslon nylon. Capacidad: 16 litros. Compartimiento para notebook 15,4. Doble cierre de alta calidad. Espaldar ergonomico con Airpassage.									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 1491,37				</div>
								</div>
	</div>

			<hr>
	
	
			<pagebreak>
			
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>M901</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Mochila portanotebook wagner macht luxus confeccionada en waterpoof taslon nylon. Compartimiento para notebook y tablet. Bolsillo de seguridad y espaldar anatómico. Capacidad: 56 litros.									<br>
					Incluye logo bordado.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 1618,52				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>O275</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Set Gaucho. Incluye: Cuchillo y tenedor parrilleros Stainless Steel. Estuche de cuero ecológico negro con broche de velcro.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 169,24				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>O071</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Resistente linterna para exterior con luz de 1W, cuerpo de aluminio e incluye funda Swiss Peak. Utiliza 3 pilas AAA no incluídas. Material: Aluminio. Medidas: 14,8 x 3,3 cm.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 398,85				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>O070</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Martillo multifuncional con elementos de acero inoxidable y 7 funciones. Incluye estuche negro. Material: Acero inoxidable y Aluminio. Medidas: 2,3 x 7,1 x 13,8 cm.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 541,90				</div>
								</div>
	</div>

			<hr>
	
	
			<pagebreak>
			
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>O072</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Cuchillo Multifulcional que dispone de 8 funciones, es de acero inoxidable negro. Incluye juego de 9 cabezales y funda. Material: Acero inoxidable y Aluminio. Medidas: 4,3 x 14,3 x 15,5 cm.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 589,59				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>W624</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Paraguas Wagner Stich de alta resistencia e impermeabilidad. Apertura automática. Mango de plástico cubierto de goma. Diámetro: 105 cm. Color azul, rojo o negro.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 362,52				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>W001</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Realizado en poliester 190T y Pongee. Sistema Wind Proof dual flex. Costillas/Ribs de Nylon, otorgándole resistencia y flexibilidad. Mango plástico con rubber coating. Incluye packaging de cartón negro mate con logo Wagner. Largo: 95 cms. Diametro 120 cms.									<br>
					Incluye 1 logo a 1 color.							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 489,67				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>W622</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Paraguas Wagner Flöz de alta resistencia e impermeabilidad, doble capa. Diámetro: 150 cm. Color azul, negro y gris claro.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 489,67				</div>
								</div>
	</div>

			<hr>
	
	
			<pagebreak>
			
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>P422</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Portfolio Cross confeccionado en cuero ecológico Cross con cierre, ganchos tipo carpeta. Interior con bolsillo, tarjetero y lapicero. Medidas: 35 x 26 x 3 cm.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 268,08				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>P660</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Portfolio Faux confeccionado en gamuza sintética con detalles en cuero ecológico. Posee cierre y lazo con hebilla para una mejor seguridad. En su interior tiene un compartimento para hojas, 2 porta-tarjeta y 1 porta-bolígrafo. Soporte para block de hojas (incluye anotador) y con sistema de 2 ganchos para hojas con anillos (ambas para hojas A4). Medida: 35 x 26 x 3 cms.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 278,88				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>P896</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Portfolio Neo. Confeccionado en cuero ecológico PU Leather de alta calidad. Cierre negro mate.  Dos Bolsillos porta documentos amplios.  Compartimiento con cierre. Porta tarjetas.  Porta Bolígrafo. Block de notas A4.  Tamaño 34*27*3,5 cm. (azul francia o gris)									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 297,64				</div>
								</div>
	</div>

			<hr>
	
	
	
	<div style="margin-top: 20px;">
		<div style="float: left; margin: 0; width: 35%; text-align: center; height: 1px;">
						<img src="/estimate/get-pdf/9526.pdf" height="100" alt="">		</div>
		<div style="float: left; margin: 0; width: 60%;">
			<div style="margin: 0; width: 58%;">
				<b>V966</b>
			</div>
						<div style="margin: 0; width: 58%; float: left;">
				Set de vino con sacacorchos neumático, una aguja de aluminio que penetra el corcho e inyecta aire. Incluye Pico vertedor. En caja negra. Medidas: 23 x 13 x 6 cm.									<br>
					Incluye 1 logo a 1 color.
							</div>
							<div style="float: left; margin: 0; width: 25%; text-align: center; height: 1px;">
					50				</div>
				<div style="float: left; margin: 0; text-align: center; height: 1px;">
					$ 330,73				</div>
								</div>
	</div>

	
</pagebreak></pagebreak></pagebreak></pagebreak></body></html>`

**Comment by bbsnly** [comment]
@stupidusername I had the same problem and I had to downgrade to the `v6.1.4` to make it work.

**Comment by jukka-p** [comment]
We encountered this problem as well and only with multi-paged documents. I first isolated the problem to our footers, of which there were two, one for the first page and another for the pages after that. From there on I found that `<DIV>` with `height` was failing for both.

Simplified example:
CSS:
```
@media print {
  @page:first {
    footer: html_InvoiceFooter;
    margin-bottom: 100mm;
  }
  @page {
    footer: html_InvoiceFooter2;
    margin-bottom: 20mm;
  }
}

div.failing-part {
  height: 15mm;
}

div.failing-footer {
  height: 20mm;
}
```
HTML:
```
<htmlpagefooter name="InvoiceFooter2">
  <div class="failing-footer" />
</htmlpagefooter>

<htmlpagefooter name="InvoiceFooter">
  <div>
    <div class="failing-part" />
  </div>
</htmlpagefooter>

```

Workaround for us was to replace `height` with `padding`, though that will work only for cases where the content of the div is somewhat static.

I'll try to post a complete example with the used options later on.

Note that the `height` is not utterly broken, as it usually works and it's possible that the required amount of pages for this problem to show up is more than two. Our document had four pages.

**Comment by stupidusername** [comment]
@jukka-p I used your sample code to reproduce the issue successfully. I just had to add a `<pagebreak />` tag. Like this:

`<htmlpagefooter name="InvoiceFooter2">
  <div class="failing-footer" />
</htmlpagefooter>

<pagebreak />

<htmlpagefooter name="InvoiceFooter">
  <div>
    <div class="failing-part" />
  </div>
</htmlpagefooter>
`

I tested this on v7.0.3. @finwe does this work as a sample/test?

**Comment by Klap-in** [comment]
The test(s) is(are) added to this directory: https://github.com/mpdf/mpdf/tree/development/tests/Issues. 
So if you could provide it in similar shape, creating the needed test(s) is quickly done :-)
