### ISSUE TITLE
PHP error using addtional fonts (mPDF v7x)

### ISSUE THREAD

**Issue by RossAWaddell** [mpdf/mpdf#674]
### I found this bug / would like to have this new functionality
Get PHP error when including additional fonts (although when I comment out Roboto I still get the error but it mentions the dejavu fonts). I have the ttf font files in a separate directory, and I notice mPDF creates a ttfonts folder in my tmp directory, but it's empty (when I first encontered this problem, there were a bunch of files there for my fonts, but not all fonts). The bigger problem is that if I turn off debug the resulting PDF is not the same as the HTML.

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
mPDF: "mpdf/mpdf": "^7.0" (from composer.json file)

PHP: 5.6.32
### This is a PHP code snippet I use

```
<?php
ob_start();
.
.
(bunch of HTML/php stuff)
.
.
    $html=ob_get_contents();    
    ob_end_clean();
    
    $defaultConfig = (new Mpdf\Config\ConfigVariables())->getDefaults();
    $fontDirs = $defaultConfig['fontDir'];

    $defaultFontConfig = (new Mpdf\Config\FontVariables())->getDefaults();
    $fontData = $defaultFontConfig['fontdata'];

    $mpdf = new \Mpdf\Mpdf([
        'debug' => true,
        'debugfonts' => true,
        'showImageErrors' => true,
        'format' => 'letter-L',
        'margin_left' => 13,
        'margin_right' => 13,
        'margin_top' => 13,
        'margin_bottom' => 13,
        'tempDir' => '../../../../private/contest/tmp',
        
        'fontDir' => array_merge($fontDirs, [
           '../../../../private/contest/include/ttfonts',]),   
        'fontdata' => $fontData + [
            'roboto' => [
                'R' => 'Roboto-Regular.ttf',
                'I' => 'Roboto-Italic.ttf',
                'B' => 'Roboto-Bold.ttf'],
            'oxygenmono' => [
                'R' => 'OxygenMono-Regular.ttf'],
            'librebarcode39extended' => [
                'R' => 'LibreBarcode39Extended-Regular.ttf']
            ],
        //'default_font' => 'arial',
        
        'orientation' => 'L']);
    
    $mpdf->WriteHTML(utf8_encode($html));
    $mpdf->Output($html ,\Mpdf\Output\Destination::INLINE);
```

### PHP Error log

> [06-Mar-2018 16:17:23 America/Toronto] PHP Fatal error:  Uncaught exception 'Mpdf\MpdfException' with message 'Number of horizontal metrics is 0' in /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/TTFontFile.php:982
> Stack trace:
> #0 /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/TTFontFile.php(292): Mpdf\TTFontFile->extractInfo(true, true, 0)
> #1 /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/Fonts/MetricsGenerator.php(24): Mpdf\TTFontFile->getMetrics('/Users/rwaddell...', 'dejavuserifcond...', 0, true, true, 0)
> #2 /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/Mpdf.php(3826): Mpdf\Fonts\MetricsGenerator->generateMetrics('/Users/rwaddell...', Array, 'dejavuserifcond...', 0, true, true, 0, false)
> #3 /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/Mpdf.php(4113): Mpdf\Mpdf->AddFont('dejavuserifcond...', '')
> #4 /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include in /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/TTFontFile.php on line 982

**Comment by RossAWaddell** [comment]
If I'm using the latest mPDF v7.x version, is there an earlier version that would work?

**Comment by jakejackson1** [comment]
@RossAWaddell your example is too verbose in some regards, and not verbose enough in others. 

To elaborate on that:

1. Is the issue related to your custom fonts at all? What if you remove the custom fonts, does the issue continue to occur? Great. We've narrowed down the problem. If not, is it a specific font causing the problem? Great. Remove the unrelated fonts from the config and we've narrowed down the problem. What if you re-download the font from the source? ect.
2. Does the error occur with debugging on/off? Or do those settings not make a difference? 
3. What about the default margins you set? Do they matter? If not, remove them. 
4. Do the same steps as above for the remaining configuration.
5. Done that? Great. Now...
6. What's the minimum HTML mark-up required to replicate the issue? And I'm talking absolute minimum (as in, if I take a single line of code out I won't be able to replicate the problem). 

We've developers who want to help make Mpdf better, and help you at the same time, but we can't do it if don't have a solid foundation to work from.

**Comment by RossAWaddell** [comment]
Here's what I tried but I still get a blank browser window and errors in my PHP log:

PHP File
...
    ob_start();
... (HTML)
    $html = ob_get_clean();
    $mpdf = new \Mpdf\Mpdf([
        //'debug' => true,
        //'debugfonts' => true,
        //'showImageErrors' => true,
        'format' => 'letter-L',
//        'margin_left' => 13,
//        'margin_right' => 13,
//        'margin_top' => 13,
//        'margin_bottom' => 13,
        'tempDir' => '../../../../private/contest/tmp']);    
//    $stylesheet = file_get_contents('../css/printout.css');
//    $mpdf->WriteHTML($stylesheet,1); // The parameter 1 tells that this is css/style only and no body/html/text
    $mpdf->WriteHTML($html);
    $mpdf->Output($html ,\Mpdf\Output\Destination::INLINE); 

I ran my HTML through a few different validators and it came up clean (no errors). 

I see a ttfontdata folder in my /tmp directory that has a bunch of files for dejavu*

PHP error log
[10-Mar-2018 12:41:54 America/Toronto] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/mpdf/mpdf/src/Mpdf.php on line 3521

This isn't the same error as before. If I comment out my tempDir setting I still get the same result.

Attached is a file I saved with my HTML.

**Comment by bjauy** [comment]
I've managed to replicate the issue adding just `'debugfonts' => true` to constructor and removing generated files from `tmpDir`.

```PHP
<?php

require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
    //'debug' => true,
    'debugfonts' => true,
]);

$mpdf->WriteHTML('<h1 >Hello world!</h1>');

$mpdf->Output();
```

Error message:

    Fatal error:  Uncaught Mpdf\MpdfException: Number of horizontal metrics is 0 in /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/TTFontFile.php:982
    Stack trace:
    #0 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/TTFontFile.php(292): Mpdf\TTFontFile->extractInfo(true, true, 0)
    #1 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/Fonts/MetricsGenerator.php(24): Mpdf\TTFontFile->getMetrics('/home/devtest/de...', 'dejavuserifcond...', 0, true, true, 0)
    #2 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/Mpdf.php(3837): Mpdf\Fonts\MetricsGenerator->generateMetrics('/home/devtest/de...', Array, 'dejavuserifcond...', 0, true, true, 0, false)
    #3 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/Mpdf.php(4125): Mpdf\Mpdf->AddFont('dejavuserifcond...', '')
    #4 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/Mpdf.php(12597): Mpdf\Mpdf->SetFont('dejavuserifcond...')
    #5 /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/Mpdf.php(1455): Mpdf\Mpdf->SetDefaultFont('serif')
    #6 /home/devtest/dev/mpdf_test/index2.php(8): Mpdf\Mpdf->__construct(Array)
    #7  in /home/devtest/dev/mpdf_test/vendor/mpdf/mpdf/src/TTFontFile.php on line 982

After commenting out `debugfonts`, fonts and document are generated without any issue. Further enabling `debugfonts` will not trigger the error until `ttfontdata` has been removed again.

PHP: 7.2.10
mpdf: v7.1.4

**Comment by bjauy** [comment]
If `read_ushort` reads 2 bytes, then

https://github.com/mpdf/mpdf/blob/b69e0015a5005ccaff8187bd607f1c2eddef46c9/src/TTFontFile.php#L963-L971

debug branch should probably skip 30, not 28 bytes. After changing `skip()` value to 30, the document was created successfully.

There were probably few other places with similar "off by two bytes" behaviour but those haven't thrown an exception. I think it would be nice to change those other values as well.

Can any of devs confirm this? If my solution is correct, I can create PR for it, if needed.

**Comment by webdreamsCH** [comment]
The problem is, no temporary font data is written. By setting tempDir to '/custom/lib/mpdf/tmp', this can be easily observed. If you want to add your own fonts and the property 'debug' => true is set, the temporary font data is not written and this leads to the strange MpdfException "Number of horizontal metrics is 0". To avoid this you can simply set 'debug' => false and generate a PDF. So the temporary font data will be written. Unpleasant but a way to trick the bug out.
